const ApiRoutes = {
    LOGIN:{
        path:'/login',
        authenticate:false
    },
    SIGNUP:{
        path:'/signup',
        authenticate:false
    },
    USERS:{
        path:'/user',
        authenticate:true
    }
    ,
    ForgotMail:{
        path:'/ForgotMail',
        authenticate:true
    },
    RecoveryMail:{
        path:'/RecoveryMail',
        authenticate:true
    },
    Reset:{
        path:'/ResetPass',
        authenticate:true
    },
    DarftMail:{
        path:'/save-draft',
        authenticate:true
    }
    ,
    SentMail:{
        path:'/save',
        authenticate:true
    },
    ToggleStarredEmail:{
        path:'/starred',
        authenticate:true
    },
    ToggleImportantEmails:{
        path:'/important',
        authenticate:true
    },
    GetEmailFromType:{
        path:'/emails',
        authenticate:true
    },
    MoveEmailsToBin:{
        path:'/bin',
        authenticate:true
    },
    DeleteEmails:{
        path:'/delete',
        authenticate:true
    },
}

export default ApiRoutes